var enLang = {
  multiEncryptor : "Multi encrypter",
  availableCiphers : "Available ciphers",
  substitutionCiphers : "Substitution ciphers",
  transpositionCiphers : "Transposition ciphers",
  graphicalCiphers : "Graphical ciphers",
  general : "General",
  chosenCiphers : "Chosen ciphers",
  inputText : "Input text",
  outputs : "Outputs",
  removePipe : "Remove Pipe",
  addPipe : "Add pipe",
  pipe : "Pipe",
  infoTypeSomeText : "Type some text",
  infoWriteCipherName : "write cipher name",
  warnTooLong : "That is too long!",
  changeLanguage: "Change language",
  Caesar : "Caesar",
  Morse : "Morse alphabet"
};

var csLang = {
  multiEncryptor : "Multi šifrovač",
  availableCiphers : "Šifry k dispozici",
  substitutionCiphers : "Substituční šifry",
  transpositionCiphers : "Transpoziční šifry",
  graphicalCiphers : "Grafické šifry",
  general : "Obecné",
  chosenCiphers : "Vybrané šifry",
  inputText : "Vstupní text",
  outputs : "Výstupy",
  removePipe : "Odebrat rouru",
  addPipe : "Přidat rouru",
  pipe : "Roura",
  infoTypeSomeText : "Napiš nějaký text",
  infoWriteCipherName : "napiš jméno šifry",
  warnTooLong : "To je moc dlouhé!",
  changeLanguage: "Změnit jazyk",
  Caesar : "Caesar",
  Morse : "Morseova abeceda"
};
