var enLang = {
  defaultInputText : "Secret message.",
  multiEncryptor : "Multi encrypter",
  availableCiphers : "Available ciphers",
  substitutionCiphers : "Substitution ciphers",
  transpositionCiphers : "Transposition ciphers",
  graphicalCiphers : "Graphical ciphers",
  universal : "Universal",
  chosenCiphers : "Chosen ciphers",
  inputText : "Input text",
  outputs : "Outputs",
  copyOutput : "Copy output into clipboard",
  infoOutputCopied : "Output was copied to clipboard",
  removePipe : "Remove Pipe",
  addPipe : "Add pipe",
  pipe : "Pipe",
  infoTypeSomeText : "Type some text",
  infoWriteCipherName : "write cipher name",
  warnTooLong : "That is too long!",
  changeLanguage: "Change language",
  useCipher: "Use this cipher",

  caesar: "Caesar",
  caesarDesc: "Every letter will be replaced with letter in alphabet which is a little further",
  lowercase: "Lowercase",
  lowercaseDesc: "Replace lower case letters with upper case",
  morse: "Morse",
  morseDesc: "Every letter is replaces with a group of one to four dots and dashes",
  nothing: "Nothing",
  nothingDesc: "Text will remain unchanged",
  removeDiacritics: "Remove diacritics",
  removeDiacriticsDesc: "Removes diacritics",
  removePunctuation: "Remove punctuation",
  removePunctuationDesc: "Removes punctuation",
  removeWhitespace: "Remove whitespace",
  removeWhitespaceDesc: "Remove spaces, tabs and newlines",
  reverse: "Reverse",
  reverseDesc: "Reveres the order of letters",
  uppercase: "Uppercase",
  uppercaseDesc: "Replaces lower case letters with upper case",
  zigZag: "Zig-zag",
  zigZagDesc: "Every second letter will be on the next line"
};

var csLang = {
  defaultInputText : "Tajná zpráva.",
  multiEncryptor : "Multi šifrovač",
  availableCiphers : "Šifry k dispozici",
  substitutionCiphers : "Substituční šifry",
  transpositionCiphers : "Transpoziční šifry",
  graphicalCiphers : "Grafické šifry",
  universal : "Všeobecné",
  chosenCiphers : "Vybrané šifry",
  inputText : "Vstupní text",
  outputs : "Výstupy",
  copyOutput : "Kopírovat výstup do schránky",
  infoOutputCopied : "Výstup byl zkopírován do schránky",
  removePipe : "Odebrat rouru",
  addPipe : "Přidat rouru",
  pipe : "Roura",
  infoTypeSomeText : "Napiš nějaký text",
  infoWriteCipherName : "napiš jméno šifry",
  warnTooLong : "To je moc dlouhé!",
  changeLanguage: "Změnit jazyk",
  useCipher: "Použij tuto šifru",

  caesar: "Caesar",
  caesarDesc: "Každé písmeno je nahrazeno písmenem v abecedě o několik dále",
  lowercase: "Malá písmena",
  lowercaseDesc: "Převede všechna velká písmena na malá",
  morse: "Morseova abeceda",
  morseDesc: "Každé písmeno je nahrazeno skupinou jedné až čtyř teček a čárek",
  nothing: "Nic",
  nothingDesc: "Text zůstane beze změny",
  removeDiacritics: "Odstranit diakritiku",
  removeDiacriticsDesc: "Odstraní diakritiku",
  removePunctuation: "Odstranit interpunkci",
  removePunctuationDesc: "Odstraní tečky, čárky, vykřičníky a podobné znaky",
  removeWhitespace: "Odstranit mezery",
  removeWhitespaceDesc: "Odstraní mezery, tabulátory a zalomení řádků",
  reverse: "Obráceně",
  reverseDesc: "Obrátí pořadí písmen",
  uppercase: "Velká písmena",
  uppercaseDesc: "Převede všechna malá písmena na velká",
  zigZag: "Cik-cak",
  zigZagDesc: "Každé druhé písmeno bude v následujícím řádku"
};
